### ISSUE TITLE
turtle-1.5.15 no longer compiles with ghc-8.2.2 or older

### ISSUE THREAD

**Issue by peti** [Gabriel439/Haskell-Turtle-Library#362]
I'm getting errors like the following:

~~~~
src/Turtle/Bytes.hs:790:32: error: 
    • Variable not in scope: (<>) :: a -> p -> t1 
    • Perhaps you meant one of these: 
        ‘<$>’ (imported from Prelude), ‘*>’ (imported from Prelude), 
        ‘<$’ (imported from Prelude) 
    | 
790 |             let bytes = prefix <> suffix 
    |                                ^^ 
~~~~

See https://travis-ci.org/peti/distribution-opensuse/builds/589054086 for more details.

I suppose this is fine, but there should be a  version constraint on `base` to prevent cabal from picking that version of `turtle` when compiling with ghc 8.2.2 or earlier.

**Comment by Gabriel439** [comment]
Actually, this is just a mistake since CI wasn't test older GHC versions.  I'll fix CI to test 8.2.2 and fix this code to not depend on an implicit `<>` in scope

**Comment by Gabriel439** [comment]
I fixed this in `master` and I also added a revision to fix the bounds on `base` for `turtle-1.5.15`
